### ISSUE TITLE
Crash at CoreGraphics`CGPDFSecurityManagerCreateDecryptor:

### ISSUE THREAD

**Issue by xuanzi23** [wolfmcnally/SwiftUIPrint#1]
CoreGraphics`CGPDFSecurityManagerCreateDecryptor:
    0x1b281cf28 <+0>:   sub    sp, sp, #0x50             ; =0x50 
    0x1b281cf2c <+4>:   stp    x24, x23, [sp, #0x10]
    0x1b281cf30 <+8>:   stp    x22, x21, [sp, #0x20]
    0x1b281cf34 <+12>:  stp    x20, x19, [sp, #0x30]
    0x1b281cf38 <+16>:  stp    x29, x30, [sp, #0x40]
    0x1b281cf3c <+20>:  add    x29, sp, #0x40            ; =0x40 
    0x1b281cf40 <+24>:  cbz    x0, 0x181dd0fe0           ; <+184>
    0x1b281cf44 <+28>:  ldr    x8, [x0, #0x10]
    0x1b281cf48 <+32>:  cbz    x8, 0x181dd0fe0           ; <+184>
->  0x1b281cf4c <+36>:  ldrb   w8, [x8, #0xb8]
    0x1b281cf50 <+40>:  cbz    w8, 0x181dd0fe0           ; <+184>
    0x1b281cf54 <+44>:  mov    x19, x3
    0x1b281cf58 <+48>:  mov    x20, x2
    0x1b281cf5c <+52>:  cbz    x1, 0x181dd0f9c           ; <+116>
    0x1b281cf60 <+56>:  ldp    x21, x22, [x1, #0x18]
    0x1b281cf64 <+60>:  cbz    x20, 0x181dd0fa8          ; <+128>
    0x1b281cf68 <+64>:  mov    x1, x20
    0x1b281cf6c <+68>:  bl     0x181dd0b44               ; CGPDFSecurityManagerCreateCryptFilter
    0x1b281cf70 <+72>:  cbz    x0, 0x181dd0fd0           ; <+168>
    0x1b281cf74 <+76>:  mov    x23, x0
    0x1b281cf78 <+80>:  mov    x1, x21
    0x1b281cf7c <+84>:  mov    x2, x22
    0x1b281cf80 <+88>:  mov    x3, x19
    0x1b281cf84 <+92>:  bl     0x181eda1b0               ; CGPDFCryptFilterCreateDecryptor
    0x1b281cf88 <+96>:  mov    x19, x0
    0x1b281cf8c <+100>: mov    x0, x23
    0x1b281cf90 <+104>: bl     0x181fb3560               ; symbol stub for: PDAdarkenPDA(_rgbaf16_t, float, _rgbaf16_t, float)
    0x1b281cf94 <+108>: mov    x0, x19
    0x1b281cf98 <+112>: b      0x181dd0fe4               ; <+188>
    0x1b281cf9c <+116>: mov    x21, #0x0
    0x1b281cfa0 <+120>: mov    x22, #0x0
    0x1b281cfa4 <+124>: cbnz   x20, 0x181dd0f68          ; <+64>
    0x1b281cfa8 <+128>: ldr    x0, [x0, #0x20]
    0x1b281cfac <+132>: mov    x1, x21
    0x1b281cfb0 <+136>: mov    x2, x22
    0x1b281cfb4 <+140>: mov    x3, x19
    0x1b281cfb8 <+144>: ldp    x29, x30, [sp, #0x40]
    0x1b281cfbc <+148>: ldp    x20, x19, [sp, #0x30]
    0x1b281cfc0 <+152>: ldp    x22, x21, [sp, #0x20]
    0x1b281cfc4 <+156>: ldp    x24, x23, [sp, #0x10]
    0x1b281cfc8 <+160>: add    sp, sp, #0x50             ; =0x50 
    0x1b281cfcc <+164>: b      0x181eda1b0               ; CGPDFCryptFilterCreateDecryptor
    0x1b281cfd0 <+168>: str    x20, [sp]
    0x1b281cfd4 <+172>: adrp   x0, 995
    0x1b281cfd8 <+176>: add    x0, x0, #0xbc3            ; =0xbc3 
    0x1b281cfdc <+180>: bl     0x181d3fe9c               ; pdf_error
    0x1b281cfe0 <+184>: mov    x0, #0x0
    0x1b281cfe4 <+188>: ldp    x29, x30, [sp, #0x40]
    0x1b281cfe8 <+192>: ldp    x20, x19, [sp, #0x30]
    0x1b281cfec <+196>: ldp    x22, x21, [sp, #0x20]
    0x1b281cff0 <+200>: ldp    x24, x23, [sp, #0x10]
    0x1b281cff4 <+204>: add    sp, sp, #0x50             ; =0x50 
    0x1b281cff8 <+208>: ret    

Do you face this issue?

**Comment by wolfmcnally** [comment]
I have not been able to replicate this. Does it always happen for you?

**Comment by andrefrank** [comment]
I ran into the same issue while trying to follow your sample code using Xcode 13.1/MacOS BigSur 11.6.2 and under Deployment target IOS 14 within the IOS Simulator. 
It seems to be a problem in the current IOS Simulator configuration environment. On a real device it works for me..

**Comment by wolfmcnally** [comment]
I replicated this problem, and I think I fixed it in the latest version.
